// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.jflex

package com.example.diagramadorcompi1.Analizadores;

import java_cup.runtime.Symbol;
import java.util.LinkedList;
import com.example.diagramadorcompi1.Modelos.SintaxError;
import com.example.diagramadorcompi1.Modelos.Token;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  2,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  4,  5,  6,  0,  7,  8,  0,  9, 10, 11, 12, 13, 14, 15, 16, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  0,  0, 18, 19, 20,  0, 
     0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 31, 32, 33, 34, 
    35, 36, 37, 38, 39, 40, 41, 42, 43, 30, 44,  0,  0,  0,  0, 45, 
     0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 
    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,  0, 46,  0,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\2\2\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\16\17\1\20\1\21\1\0\1\22\5\0"+
    "\1\23\1\0\1\24\1\25\1\26\17\17\1\27\3\17"+
    "\1\30\5\0\1\31\5\17\1\32\12\17\1\33\1\17"+
    "\1\34\4\0\12\17\1\35\7\17\4\0\1\36\5\17"+
    "\1\37\1\17\1\40\5\17\1\41\2\17\4\0\6\17"+
    "\1\42\6\17\4\0\1\43\1\17\1\44\2\17\1\45"+
    "\1\17\1\46\3\17\1\47\4\0\1\50\2\0\1\17"+
    "\1\51\1\17\1\52\3\17\2\0\1\53\7\0\5\17"+
    "\5\0\1\54\2\0\1\55\1\56\2\17\1\57\1\17"+
    "\10\0\1\60\3\17\10\0\3\17\1\61\7\0\1\62"+
    "\2\17\4\0\1\63\1\0\1\64\4\0\2\17\1\65"+
    "\2\0\1\66\4\0\1\67\1\17\1\70\2\0\1\71"+
    "\1\72\2\0\1\17\4\0\1\17\4\0\1\17\1\73"+
    "\1\0\1\74\1\0\1\17\2\0\1\17\1\75\1\76"+
    "\1\77";

  private static int [] zzUnpackAction() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\57\0\57\0\57\0\57\0\57\0\57\0\57\0\u0178"+
    "\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1\0\u02f0"+
    "\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db\0\u040a\0\u0439\0\u0468"+
    "\0\u0497\0\u04c6\0\57\0\274\0\57\0\u04f5\0\u0524\0\u0553"+
    "\0\u0582\0\u05b1\0\57\0\u05e0\0\57\0\57\0\57\0\u060f"+
    "\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787"+
    "\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u0263\0\u08d0"+
    "\0\u08ff\0\u092e\0\57\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19"+
    "\0\u05e0\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62"+
    "\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda"+
    "\0\u0d09\0\u0263\0\u0d38\0\57\0\u0d67\0\u0d96\0\u0dc5\0\u0df4"+
    "\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0263\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5"+
    "\0\u10e4\0\u1113\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u0263\0\u11fe"+
    "\0\u122d\0\u125c\0\u128b\0\u12ba\0\u0263\0\u12e9\0\u0263\0\u1318"+
    "\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u0263\0\u1403\0\u1432\0\u1461"+
    "\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa\0\u15d9"+
    "\0\u1608\0\u0263\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u1722"+
    "\0\u1751\0\u1780\0\u17af\0\u17de\0\u0263\0\u180d\0\u0263\0\u183c"+
    "\0\u186b\0\u0263\0\u189a\0\u0263\0\u18c9\0\u18f8\0\u1927\0\u0263"+
    "\0\u1956\0\u1985\0\u19b4\0\u19e3\0\57\0\u1a12\0\u1a41\0\u1a70"+
    "\0\u0263\0\u1a9f\0\u0263\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a"+
    "\0\57\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u1c75\0\u1ca4\0\u1cd3"+
    "\0\u1d02\0\u1d31\0\u1d60\0\u1d8f\0\u1dbe\0\u1ded\0\u1e1c\0\u1e4b"+
    "\0\u1e7a\0\u1ea9\0\57\0\u1ed8\0\u1f07\0\u1f36\0\u0263\0\u1f65"+
    "\0\u1f94\0\u1fc3\0\u1ff2\0\u2021\0\u2050\0\u207f\0\u20ae\0\u20dd"+
    "\0\u210c\0\u213b\0\u216a\0\u0263\0\u2199\0\u21c8\0\u21f7\0\u2226"+
    "\0\u2255\0\u2284\0\u22b3\0\u22e2\0\u2311\0\u2340\0\u236f\0\u239e"+
    "\0\u23cd\0\u23fc\0\57\0\u242b\0\u245a\0\u2489\0\u24b8\0\u24e7"+
    "\0\u2516\0\u2545\0\u0263\0\u2574\0\u25a3\0\u25d2\0\u2601\0\u2630"+
    "\0\u265f\0\57\0\u268e\0\57\0\u26bd\0\u26ec\0\u271b\0\u274a"+
    "\0\u2779\0\u27a8\0\57\0\u27d7\0\u2806\0\57\0\u2835\0\u2864"+
    "\0\u2893\0\u28c2\0\57\0\u28f1\0\u0263\0\u2920\0\u294f\0\57"+
    "\0\57\0\u297e\0\u29ad\0\u29dc\0\u2a0b\0\u2a3a\0\u2a69\0\u2a98"+
    "\0\u2ac7\0\u2af6\0\u2b25\0\u2b54\0\u2b83\0\u2bb2\0\57\0\u2be1"+
    "\0\57\0\u2c10\0\u2c3f\0\u2c6e\0\u2c9d\0\u2ccc\0\57\0\57"+
    "\0\u0263";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\25"+
    "\1\27\1\30\1\25\1\31\1\32\1\25\1\33\1\34"+
    "\2\25\1\35\1\25\1\36\1\37\1\40\1\25\1\41"+
    "\4\25\1\42\60\0\2\3\77\0\1\43\33\0\5\44"+
    "\1\45\51\44\2\6\2\0\53\6\7\0\1\46\17\0"+
    "\1\47\1\50\1\0\1\51\4\0\1\52\27\0\1\53"+
    "\65\0\1\54\1\0\1\20\60\0\1\55\56\0\1\56"+
    "\56\0\1\57\54\0\1\25\3\0\20\25\1\60\10\25"+
    "\22\0\1\25\3\0\31\25\22\0\1\25\3\0\10\25"+
    "\1\61\4\25\1\62\13\25\22\0\1\25\3\0\2\25"+
    "\1\63\11\25\1\64\14\25\22\0\1\25\3\0\10\25"+
    "\1\65\20\25\22\0\1\66\3\0\1\67\5\66\23\25"+
    "\22\0\1\25\3\0\14\25\1\70\14\25\22\0\1\25"+
    "\3\0\4\25\1\71\24\25\22\0\1\25\3\0\10\25"+
    "\1\72\4\25\1\73\13\25\22\0\1\25\3\0\1\74"+
    "\30\25\22\0\1\25\3\0\4\25\1\75\10\25\1\76"+
    "\13\25\22\0\1\25\3\0\10\25\1\77\20\25\22\0"+
    "\1\25\3\0\10\25\1\100\20\25\22\0\1\25\3\0"+
    "\1\101\3\25\1\102\24\25\57\0\1\103\7\0\1\104"+
    "\111\0\1\105\45\0\1\106\62\0\1\107\52\0\1\110"+
    "\46\0\1\111\56\0\1\25\3\0\10\25\1\112\20\25"+
    "\22\0\1\25\3\0\20\25\1\113\10\25\22\0\1\25"+
    "\3\0\13\25\1\114\15\25\22\0\1\25\3\0\12\25"+
    "\1\115\16\25\22\0\1\25\3\0\22\25\1\116\6\25"+
    "\22\0\1\25\3\0\14\25\1\117\14\25\22\0\1\120"+
    "\3\0\6\120\23\25\22\0\1\120\3\0\2\120\1\121"+
    "\3\120\23\25\22\0\1\25\3\0\10\25\1\122\20\25"+
    "\22\0\1\25\3\0\4\25\1\123\24\25\22\0\1\25"+
    "\3\0\4\25\1\124\24\25\22\0\1\25\3\0\21\25"+
    "\1\125\7\25\22\0\1\25\3\0\20\25\1\126\10\25"+
    "\22\0\1\25\3\0\2\25\1\127\26\25\22\0\1\25"+
    "\3\0\13\25\1\130\15\25\22\0\1\25\3\0\13\25"+
    "\1\131\15\25\22\0\1\25\3\0\20\25\1\132\10\25"+
    "\22\0\1\25\3\0\20\25\1\133\10\25\10\0\1\134"+
    "\106\0\1\135\51\0\1\136\57\0\1\137\72\0\1\140"+
    "\30\0\1\25\3\0\1\141\30\25\22\0\1\25\3\0"+
    "\2\25\1\142\26\25\22\0\1\25\3\0\10\25\1\143"+
    "\20\25\22\0\1\25\3\0\10\25\1\144\20\25\22\0"+
    "\1\25\3\0\15\25\1\145\13\25\22\0\1\25\3\0"+
    "\13\25\1\146\5\25\1\147\7\25\22\0\1\150\3\0"+
    "\6\150\23\25\22\0\1\150\3\0\4\150\1\151\1\150"+
    "\23\25\22\0\1\25\3\0\2\25\1\152\26\25\22\0"+
    "\1\25\3\0\20\25\1\153\10\25\22\0\1\25\3\0"+
    "\14\25\1\154\14\25\22\0\1\25\3\0\22\25\1\155"+
    "\6\25\22\0\1\25\3\0\1\156\30\25\22\0\1\25"+
    "\3\0\22\25\1\157\6\25\22\0\1\25\3\0\1\25"+
    "\1\160\27\25\22\0\1\25\3\0\4\25\1\161\24\25"+
    "\22\0\1\25\3\0\3\25\1\162\25\25\43\0\1\163"+
    "\41\0\1\164\101\0\1\165\53\0\1\166\32\0\1\25"+
    "\3\0\12\25\1\167\16\25\22\0\1\25\3\0\23\25"+
    "\1\170\5\25\22\0\1\25\3\0\2\25\1\171\26\25"+
    "\22\0\1\25\3\0\16\25\1\172\12\25\22\0\1\25"+
    "\3\0\14\25\1\173\14\25\22\0\1\25\3\0\10\25"+
    "\1\174\20\25\22\0\1\25\3\0\10\25\1\175\20\25"+
    "\22\0\1\176\3\0\6\176\23\25\22\0\1\176\3\0"+
    "\6\176\12\25\1\177\10\25\22\0\1\25\3\0\10\25"+
    "\1\200\20\25\22\0\1\25\3\0\22\25\1\201\6\25"+
    "\22\0\1\25\3\0\20\25\1\202\10\25\22\0\1\25"+
    "\3\0\12\25\1\203\16\25\22\0\1\25\3\0\1\204"+
    "\30\25\22\0\1\25\3\0\15\25\1\205\13\25\22\0"+
    "\1\25\3\0\21\25\1\206\7\25\22\0\1\25\3\0"+
    "\1\207\30\25\46\0\1\210\61\0\1\211\53\0\1\212"+
    "\36\0\1\213\52\0\1\25\3\0\12\25\1\214\16\25"+
    "\22\0\1\25\3\0\30\25\1\215\22\0\1\25\3\0"+
    "\21\25\1\216\7\25\22\0\1\25\3\0\2\25\1\217"+
    "\26\25\22\0\1\25\3\0\4\25\1\220\24\25\22\0"+
    "\1\221\3\0\6\221\23\25\22\0\1\25\3\0\15\25"+
    "\1\222\13\25\22\0\1\25\3\0\20\25\1\223\10\25"+
    "\22\0\1\25\3\0\1\224\30\25\22\0\1\25\3\0"+
    "\4\25\1\225\24\25\22\0\1\25\3\0\14\25\1\226"+
    "\14\25\22\0\1\25\3\0\30\25\1\227\22\0\1\25"+
    "\3\0\14\25\1\230\14\25\56\0\1\231\40\0\1\232"+
    "\44\0\1\233\77\0\1\234\31\0\1\25\3\0\15\25"+
    "\1\235\13\25\22\0\1\25\3\0\21\25\1\236\7\25"+
    "\22\0\1\25\3\0\4\25\1\237\24\25\22\0\1\25"+
    "\3\0\4\25\1\240\24\25\22\0\1\25\3\0\14\25"+
    "\1\241\14\25\22\0\1\242\3\0\6\242\23\25\22\0"+
    "\1\25\3\0\1\243\30\25\22\0\1\25\3\0\20\25"+
    "\1\244\10\25\22\0\1\25\3\0\12\25\1\245\16\25"+
    "\22\0\1\25\3\0\6\25\1\246\22\25\22\0\1\25"+
    "\3\0\14\25\1\247\14\25\22\0\1\25\3\0\1\250"+
    "\30\25\27\0\1\251\11\0\1\252\5\0\1\253\1\254"+
    "\56\0\1\255\64\0\1\256\56\0\1\257\22\0\1\25"+
    "\3\0\1\260\30\25\22\0\1\25\3\0\21\25\1\261"+
    "\7\25\22\0\1\25\3\0\22\25\1\262\6\25\22\0"+
    "\1\25\3\0\21\25\1\263\7\25\22\0\1\25\3\0"+
    "\15\25\1\264\13\25\22\0\1\25\3\0\23\25\1\265"+
    "\5\25\22\0\1\25\3\0\4\25\1\266\24\25\40\0"+
    "\1\267\54\0\1\270\56\0\1\271\52\0\1\272\53\0"+
    "\1\273\11\0\1\274\5\0\1\275\36\0\1\276\11\0"+
    "\1\277\5\0\1\300\31\0\1\25\3\0\14\25\1\301"+
    "\14\25\22\0\1\25\3\0\20\25\1\302\10\25\22\0"+
    "\1\25\3\0\6\25\1\303\22\25\22\0\1\25\3\0"+
    "\12\25\1\304\16\25\22\0\1\25\3\0\25\25\1\305"+
    "\3\25\43\0\1\306\45\0\1\307\100\0\1\310\42\0"+
    "\1\311\54\0\1\312\56\0\1\313\60\0\1\314\54\0"+
    "\1\315\56\0\1\316\42\0\1\25\3\0\21\25\1\317"+
    "\7\25\22\0\1\25\3\0\1\320\30\25\22\0\1\25"+
    "\3\0\20\25\1\321\10\25\22\0\1\25\3\0\15\25"+
    "\1\322\13\25\22\0\1\25\3\0\30\25\1\323\45\0"+
    "\1\324\53\0\1\325\64\0\1\326\51\0\1\327\45\0"+
    "\1\330\67\0\1\331\45\0\1\332\101\0\1\333\23\0"+
    "\1\25\3\0\21\25\1\334\7\25\22\0\1\25\3\0"+
    "\1\335\30\25\22\0\1\25\3\0\30\25\1\336\22\0"+
    "\1\25\3\0\20\25\1\337\10\25\51\0\1\340\55\0"+
    "\1\341\51\0\1\342\60\0\1\343\53\0\1\344\61\0"+
    "\1\345\53\0\1\346\46\0\1\347\46\0\1\25\3\0"+
    "\13\25\1\350\15\25\22\0\1\25\3\0\20\25\1\351"+
    "\10\25\22\0\1\25\3\0\15\25\1\352\13\25\32\0"+
    "\1\353\72\0\1\354\66\0\1\355\51\0\1\356\55\0"+
    "\1\357\57\0\1\360\55\0\1\361\64\0\1\362\22\0"+
    "\1\25\3\0\15\25\1\363\13\25\22\0\1\25\3\0"+
    "\4\25\1\364\24\25\22\0\1\25\3\0\13\25\1\365"+
    "\15\25\26\0\1\366\57\0\1\367\11\0\1\370\5\0"+
    "\1\371\41\0\1\372\72\0\1\373\42\0\1\374\72\0"+
    "\1\375\37\0\1\376\11\0\1\377\5\0\1\u0100\31\0"+
    "\1\25\3\0\3\25\1\u0101\25\25\22\0\1\25\3\0"+
    "\1\u0102\30\25\47\0\1\u0103\47\0\1\u0104\54\0\1\u0105"+
    "\56\0\1\u0106\46\0\1\u0107\56\0\1\u0108\70\0\1\u0109"+
    "\54\0\1\u010a\56\0\1\u010b\42\0\1\25\3\0\15\25"+
    "\1\u010c\13\25\22\0\1\25\3\0\14\25\1\u010d\14\25"+
    "\43\0\1\u010e\45\0\1\u010f\73\0\1\u0110\56\0\1\u0111"+
    "\52\0\1\u0112\45\0\1\u0113\46\0\1\25\3\0\14\25"+
    "\1\u0114\14\25\45\0\1\u0115\53\0\1\u0116\61\0\1\u0117"+
    "\53\0\1\u0118\36\0\1\25\3\0\3\25\1\u0119\25\25"+
    "\51\0\1\u011a\55\0\1\u011b\57\0\1\u011c\55\0\1\u011d"+
    "\30\0\1\25\3\0\4\25\1\u011e\24\25\32\0\1\u011f"+
    "\72\0\1\u0120\42\0\1\u0121\72\0\1\u0122\32\0\1\25"+
    "\3\0\1\u0123\30\25\26\0\1\u0124\56\0\1\u0125\52\0"+
    "\1\25\3\0\3\25\1\u0126\25\25\47\0\1\u0127\56\0"+
    "\1\u0128\31\0\1\25\3\0\15\25\1\u0129\13\25\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11515];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\7\11\23\1\1\11\1\0\1\11"+
    "\5\0\1\11\1\0\3\11\23\1\1\11\5\0\23\1"+
    "\1\11\4\0\22\1\4\0\21\1\4\0\15\1\4\0"+
    "\14\1\4\0\1\11\2\0\7\1\2\0\1\11\7\0"+
    "\5\1\5\0\1\11\2\0\6\1\10\0\4\1\10\0"+
    "\3\1\1\11\7\0\3\1\4\0\1\11\1\0\1\11"+
    "\4\0\2\1\1\11\2\0\1\11\4\0\1\11\2\1"+
    "\2\0\2\11\2\0\1\1\4\0\1\1\4\0\1\1"+
    "\1\11\1\0\1\11\1\0\1\1\2\0\1\1\2\11"+
    "\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[297];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public LinkedList<SintaxError> listaErrorLexico = new LinkedList<>();
    public static LinkedList<Token> listaTokens = new LinkedList<>();

    private void agregarToken(String lexema, String tipo){
        listaTokens.add(new Token(lexema, tipo, yyline, yycolumn));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrorLexico = new LinkedList<>();
    listaTokens = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { agregarToken(yytext(), "ERROR"); listaErrorLexico.add(new SintaxError("LEXICO", "Simbolo: "+ yytext()+" no existente en el lenguaje", yyline, yycolumn));
            }
          // fall through
          case 64: break;
          case 2:
            { 
            }
          // fall through
          case 65: break;
          case 3:
            { agregarToken(yytext(), "NOT"); return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 4:
            { agregarToken(yytext(), "LPAREN"); return new Symbol(sym.LPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 5:
            { agregarToken(yytext(), "RPAREN"); return new Symbol(sym.RPAREN, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 6:
            { agregarToken(yytext(), "MULTIPLICACION"); return new Symbol(sym.MULTIPLICACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 7:
            { agregarToken(yytext(), "SUMA"); return new Symbol(sym.SUMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 8:
            { agregarToken(yytext(), "COMA"); return new Symbol(sym.COMA, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 9:
            { agregarToken(yytext(), "RESTA"); return new Symbol(sym.RESTA, yyline, yycolumn, yytext());
            }
          // fall through
          case 72: break;
          case 10:
            { agregarToken(yytext(), "DIVISION"); return new Symbol(sym.DIVISION, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 11:
            { agregarToken(yytext(), "ENTEROS"); return new Symbol(sym.ENTEROS, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 12:
            { agregarToken(yytext(), "MENOR_QUE"); return new Symbol(sym.MENOR_QUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 13:
            { agregarToken(yytext(), "ASIGNACION"); return new Symbol(sym.ASIGNACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 14:
            { agregarToken(yytext(), "MAYOR_QUE"); return new Symbol(sym.MAYOR_QUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 15:
            { agregarToken(yytext(), "IDENTIFICADOR"); return new Symbol(sym.IDENTIFICADOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 16:
            { agregarToken(yytext(), "SEPARADOR_CONFIG"); return new Symbol(sym.SEPARADOR_CONFIG, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 17:
            { agregarToken(yytext(), "DIFERENTE"); return new Symbol(sym.DIFERENTE, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 18:
            { agregarToken(yytext(), "TEXTO"); return new Symbol(sym.TEXTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 19:
            { agregarToken(yytext(), "AND"); return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 82: break;
          case 20:
            { agregarToken(yytext(), "MENOR_IGUAL_QUE"); return new Symbol(sym.MENOR_IGUAL_QUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 83: break;
          case 21:
            { agregarToken(yytext(), "IGUALDAD"); return new Symbol(sym.IGUALDAD, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 22:
            { agregarToken(yytext(), "MAYOR_IGUAL_QUE"); return new Symbol(sym.MAYOR_IGUAL_QUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 23:
            { agregarToken(yytext(), "SI"); return new Symbol(sym.SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 24:
            { agregarToken(yytext(), "OR"); return new Symbol(sym.OR, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 25:
            { agregarToken(yytext(), "DECIMAL"); return new Symbol(sym.DECIMAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 26:
            { agregarToken(yytext(), "FIN"); return new Symbol(sym.FIN, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 27:
            { agregarToken(yytext(), "VAR"); return new Symbol(sym.VAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 28:
            { agregarToken(yytext(), "SEPARADOR"); return new Symbol(sym.SEPARADOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 29:
            { agregarToken(yytext(), "LEER"); return new Symbol(sym.LEER, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 30:
            { agregarToken(yytext(), "ARIAL"); return new Symbol(sym.ARIAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 31:
            { agregarToken(yytext(), "FINSI"); return new Symbol(sym.FINSI, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 32:
            { agregarToken(yytext(), "HACER"); return new Symbol(sym.HACER, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 33:
            { agregarToken(yytext(), "ROMBO"); return new Symbol(sym.ROMBO, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 34:
            { agregarToken(yytext(), "INICIO"); return new Symbol(sym.INICIO, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 35:
            { agregarToken(yytext(), "CIRCULO"); return new Symbol(sym.CIRCULO, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          case 36:
            { agregarToken(yytext(), "ECLIPSE"); return new Symbol(sym.ECLIPSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 99: break;
          case 37:
            { agregarToken(yytext(), "HEXADECIMAL"); return new Symbol(sym.HEXADECIMAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 100: break;
          case 38:
            { agregarToken(yytext(), "MOSTRAR"); return new Symbol(sym.MOSTRAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 101: break;
          case 39:
            { agregarToken(yytext(), "VERDANA"); return new Symbol(sym.VERDANA, yyline, yycolumn, yytext());
            }
          // fall through
          case 102: break;
          case 40:
            { agregarToken(yytext(), "DEFAULT"); return new Symbol(sym.DEFAULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 103: break;
          case 41:
            { agregarToken(yytext(), "ENTONCES"); return new Symbol(sym.ENTONCES, yyline, yycolumn, yytext());
            }
          // fall through
          case 104: break;
          case 42:
            { agregarToken(yytext(), "MIENTRAS"); return new Symbol(sym.MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 105: break;
          case 43:
            { agregarToken(yytext(), "COLOR_SI"); return new Symbol(sym.COLOR_SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 106: break;
          case 44:
            { agregarToken(yytext(), "FIGURA_SI"); return new Symbol(sym.FIGURA_SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 107: break;
          case 45:
            { agregarToken(yytext(), "LETRAS_SI"); return new Symbol(sym.LETRAS_SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 108: break;
          case 46:
            { agregarToken(yytext(), "COMIC_SANS"); return new Symbol(sym.COMIC_SANS, yyline, yycolumn, yytext());
            }
          // fall through
          case 109: break;
          case 47:
            { agregarToken(yytext(), "RECTANGULO"); return new Symbol(sym.RECTANGULO, yyline, yycolumn, yytext());
            }
          // fall through
          case 110: break;
          case 48:
            { agregarToken(yytext(), "FINMIENTRAS"); return new Symbol(sym.FINMIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 111: break;
          case 49:
            { agregarToken(yytext(), "COLOR_BLOQUE"); return new Symbol(sym.COLOR_BLOQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 112: break;
          case 50:
            { agregarToken(yytext(), "PARALELOGRAMO"); return new Symbol(sym.PARALELOGRAMO, yyline, yycolumn, yytext());
            }
          // fall through
          case 113: break;
          case 51:
            { agregarToken(yytext(), "FIGURA_BLOQUE"); return new Symbol(sym.FIGURA_BLOQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 114: break;
          case 52:
            { agregarToken(yytext(), "LETRAS_BLOQUE"); return new Symbol(sym.LETRAS_BLOQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 115: break;
          case 53:
            { agregarToken(yytext(), "COLOR_MIENTRAS"); return new Symbol(sym.COLOR_MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 116: break;
          case 54:
            { agregarToken(yytext(), "COLOR_TEXTO_SI"); return new Symbol(sym.COLOR_TEXTO_SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 117: break;
          case 55:
            { agregarToken(yytext(), "LETRAS_SIZE_SI"); return new Symbol(sym.LETRAS_SIZE_SI, yyline, yycolumn, yytext());
            }
          // fall through
          case 118: break;
          case 56:
            { agregarToken(yytext(), "TIMES_NEW_ROMAN"); return new Symbol(sym.TIMES_NEW_ROMAN, yyline, yycolumn, yytext());
            }
          // fall through
          case 119: break;
          case 57:
            { agregarToken(yytext(), "FIGURA_MIENTRAS"); return new Symbol(sym.FIGURA_MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 120: break;
          case 58:
            { agregarToken(yytext(), "LETRAS_MIENTRAS"); return new Symbol(sym.LETRAS_MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 121: break;
          case 59:
            { agregarToken(yytext(), "COLOR_TEXTO_BLOQUE"); return new Symbol(sym.COLOR_TEXTO_BLOQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 122: break;
          case 60:
            { agregarToken(yytext(), "LETRAS_SIZE_BLOQUE"); return new Symbol(sym.LETRAS_SIZE_BLOQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 123: break;
          case 61:
            { agregarToken(yytext(), "COLOR_TEXTO_MIENTRAS"); return new Symbol(sym.COLOR_TEXTO_MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 124: break;
          case 62:
            { agregarToken(yytext(), "LETRAS_SIZE_MIENTRAS"); return new Symbol(sym.LETRAS_SIZE_MIENTRAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 125: break;
          case 63:
            { agregarToken(yytext(), "RECTANGULO_REDONDEADO"); return new Symbol(sym.RECTANGULO_REDONDEADO, yyline, yycolumn, yytext());
            }
          // fall through
          case 126: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
